export { default as Navbar } from "./Navbar";
export { default as Cover } from "./Cover";
export { default as AtAGlance } from "./AtAGlance";
export { default as TechStack } from "./TechStack";
export { default as FrontendTrack } from "./FrontendTrack";
export { default as BackendTrack } from "./BackendTrack";
export { default as HowClassesWork } from "./HowClassesWork";
export { default as Projects } from "./Projects";
export { default as Testimonials } from "./Testimonials";
export { default as Enroll } from "./Enroll";
export { default as FAQ } from "./FAQ";
export { default as FinalCTA } from "./FinalCTA";
export { useCountUp } from "./useCountUp";